Swagger documentation for GroupsApiResource.java
Sanyam96/incubator-fineract pull request #11
Opened 2017-12-10 09:26 UTC by luckyman20

I haven't annotated 7th endpoint which is a POST one because there are many documentation for that endpoint according to the existing documentation as it differs in the Query Param. Please tell me solution for that

**Note** - I have not tested the changes as one endpoint is remaining to be annotated.

2017-12-19 08:32 UTC, Sanyam96 commented
@luckyman20 
Have you tested this API with Swagger-UI and completed the remaining endpoint?

2017-12-19 09:30 UTC, luckyman20 commented
Yes, I have tested it and completed the remaining endpoint.

2017-12-19 12:56 UTC, Sanyam96 requested changes
Add newline character in notes section
in most of the cases, indentation is not correct

2017-12-20 17:44 UTC, Sanyam96 approved these changes

2017-12-20 17:44 UTC, merged