Swagger Documentation for CollateralsApiResource.java
Sanyam96/incubator-fineract pull request #5
Opened 2017-12-02 16:07 UTC by luckyman000786

2017-12-03 10:55 UTC, Sanyam96 commented
Naming Convention is not correct!

2017-12-03 10:58 UTC, luckyman000786 commented
I will correct that.

2017-12-03 12:50 UTC, Sanyam96 approved these changes

2017-12-03 12:50 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
>      public String retrieveCollateralDetails(@Context final UriInfo uriInfo, @PathParam("loanId") final Long loanId,
@ApiParam annotation is missing

2017-12-03 12:51 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
> +    public String deleteCollateral(@PathParam("loanId") @ApiParam(value = "loanId") final Long loanId, @PathParam("collateralId") @ApiParam(value = "collateralId")final Long collateralId) {
response name of inner class is not correct

2017-12-04 04:14 UTC, luckyman000786 commented
@Sanyam96 I have updated the PR

2017-12-04 10:26 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
> +    @ApiResponses({@ApiResponse(code = 200, message = "OK", response = CollateralsApiResourceSwagger.DeleteLoansLoanIdCollateralIdCollatarealsResponse.class)})
naming of inner class is  not correct

2017-12-04 10:26 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
> +    @ApiResponses({@ApiResponse(code = 200, message = "OK", response = CollateralsApiResourceSwagger.PostLoansLoanIdCollateralsCollateralIdResponse.class)})
check the naming of the inner class

2017-12-04 10:26 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResourceSwagger.java
> +public class CollateralsApiResourceSwagger {
class should not be public
make it final

2017-12-04 10:29 UTC, luckyman000786 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
> +    @ApiResponses({@ApiResponse(code = 200, message = "OK", response = CollateralsApiResourceSwagger.PostLoansLoanIdCollateralsCollateralIdResponse.class)})
what should be the correct name then?

2017-12-04 10:34 UTC, Sanyam96 requested changes

2017-12-04 10:34 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
> +    @ApiResponses({@ApiResponse(code = 200, message = "OK", response = CollateralsApiResourceSwagger.PostLoansLoanIdCollateralsCollateralIdResponse.class)})
PostLoansLoanIdCollateralsResponse

2017-12-04 11:11 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/collateral/api/CollateralsApiResource.java
> +    @ApiResponses({@ApiResponse(code = 200, message = "OK", response = CollateralsApiResourceSwagger.DeleteLoansLoanIdCollatarealsCollateralIdResponse.class)})
Check the spelling of inner class

2017-12-04 11:13 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/interestratechart/api/InterestRateChartsApiResource.java
> +    public String create(@ApiParam(hidden = true) final String apiRequestBodyAsJson) {
The response for this method is missing!

2017-12-05 22:22 UTC, Sanyam96 commented
Response of GET https://DomainName/api/v1/interestratecharts/{chartId}
is not correct.

2017-12-06 08:54 UTC, Sanyam96 approved these changes

2017-12-06 08:55 UTC, merged