Swagger Documentation for InterestRateChartSlabsApiResource.java
Sanyam96/incubator-fineract pull request #8
Opened 2017-12-08 10:06 UTC by luckyman20

2017-12-09 19:13 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/interestratechart/api/InterestRateChartSlabsApiResourceSwagger.java
> +
private constructor missing

2017-12-10 02:52 UTC, luckyman20 commented
@Sanyam96 Made the Changes

2017-12-10 11:46 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/interestratechart/api/InterestRateChartSlabsApiResource.java
> +    @ApiOperation(value = "Create a Slab", httpMethod = "POST", notes = "Creates a new interest rate slab for an interest rate chart.\n" + "Example Requests:\n" + "\n" + "interestratecharts/1/chartsl
Creats a new interest rate slab for an interest rate chart.

Mandatory Fields
periodType, fromPeriod, annualInterestRate
Optional Fields
toPeriod and description
Example Requests:

interestratecharts/1/chartslabs

2017-12-10 11:46 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/interestratechart/api/InterestRateChartSlabsApiResource.java
> +    @ApiOperation(value = "Create a Slab", httpMethod = "POST", notes = "Creates a new interest rate slab for an interest rate chart.\n" + "Example Requests:\n" + "\n" + "interestratecharts/1/chartsl
All the above details in the notes section

2017-12-10 11:46 UTC, Sanyam96 requested changes

2017-12-10 11:46 UTC, Sanyam96 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/interestratechart/api/InterestRateChartSlabsApiResource.java
> +    @ApiOperation(value = "Create a Slab", httpMethod = "POST", notes = "Creates a new interest rate slab for an interest rate chart.\n" + "Example Requests:\n" + "\n" + "interestratecharts/1/chartsl
seperated by new line characters

2017-12-10 11:54 UTC, luckyman20 commented
@Sanyam96 Made the Changes

2017-12-10 12:24 UTC, Sanyam96 approved these changes

2017-12-10 12:24 UTC, merged